### ISSUE TITLE
Unable to imbue ClothingArmor

### ISSUE THREAD

**Issue by sapphire-knight** [ACEmulator/ACE-World-16PY-Patches#697]
![image](https://user-images.githubusercontent.com/69483793/97379701-bde79380-189b-11eb-96d0-891f40d0a5ce.png)

Should be able to apply armor imbues to these armor types just like regular armor.

**Comment by gmriggs** [comment]
https://github.com/ACEmulator/ACE-World-16PY-Patches/blob/2484c28b0dc3276a9c6950e3eb53fdef99088da2/Database/Patches/2005-07-ThroneOfDestiny/9%20WeenieDefaults/CraftTool/TinkeringMaterial/30106%20Foolproof%20Zircon.sql TargetType should most likely be ItemType.Vestments (Armor or Clothing), instead of just Armor

someone should be able to confirm with pcaps

**Comment by gmriggs** [comment]
confirmed: https://github.com/ACEmulator/ACE-PCAP-Exports/blob/4ed5b7d65b1f55b0f979c8d1320d114ce3068b26/Database/3-Core/9%20WeenieDefaults/SQL/CraftTool/Misc/36636%20Foolproof%20Zircon.sql
